# Generated by Django 2.1.4 on 2018-12-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(default='/default/avatar.jpg', upload_to='tourer/')),
                ('question', models.CharField(default='question', max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('info', models.CharField(max_length=250)),
                ('author', models.CharField(blank=True, choices=[('admin', 'admin'), ('account', 'account')], default='account', max_length=250, null=True)),
                ('email', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
